<?php
/**
 * Adding Themify icon set to visual composer icon-picker
 * *******************************************************
 */
add_action( 'vc_before_init', function() {
    if (class_exists('WPBMap')) {

        add_filter('init', function () {
            $param = WPBMap::getParam('vc_icon', 'type');
            $param['value'][__('Thimify Icon', 'appland-core')] = 'themify_icon';
            vc_update_shortcode_param('vc_icon', $param);
        }, 40);


// Add array of your fonts so they can be displayed in the font selector
        add_filter('vc_iconpicker-type-themify_icon', function () {
            return array(
                array('ti-wand' => esc_html__('Wand', 'appland-core')),
                array('ti-volume' => esc_html__('Volume', 'appland-core')),
                array('ti-user' => esc_html__('User', 'appland-core')),
                array('ti-unlock' => esc_html__('Unlock', 'appland-core')),
                array('ti-unlink' => esc_html__('Unlink', 'appland-core')),
                array('ti-trash' => esc_html__('Trash', 'appland-core')),
                array('ti-thought' => esc_html__('Thought', 'appland-core')),
                array('ti-target' => esc_html__('Target', 'appland-core')),
                array('ti-tag' => esc_html__('Tag', 'appland-core')),
                array('ti-tablet' => esc_html__('Tablet', 'appland-core')),
                array('ti-star' => esc_html__('Star', 'appland-core')),
                array('ti-spray' => esc_html__('Spray', 'appland-core')),
                array('ti-shopping-cart-full' => esc_html__('Shopping Cart Full', 'appland-core')),
                array('ti-shopping-cart' => esc_html__('Shopping Cart', 'appland-core')),
                array('ti-settings' => esc_html__('Settings', 'appland-core')),
                array('ti-search' => esc_html__('Search', 'appland-core')),
                array('ti-zoom-in' => esc_html__('Zoom In', 'appland-core')),
                array('ti-zoom-out' => esc_html__('Zoom Out', 'appland-core')),
                array('ti-cut' => esc_html__('Cut', 'appland-core')),
                array('ti-ruler' => esc_html__('Ruler', 'appland-core')),
                array('ti-ruler-pencil' => esc_html__('Ruler Pencil', 'appland-core')),
                array('ti-ruler-alt' => esc_html__('Ruler alt', 'appland-core')),
                array('ti-bookmark' => esc_html__('Bookmark', 'appland-core')),
                array('ti-bookmark-alt' => esc_html__('Bookmark Alt', 'appland-core')),
                array('ti-reload' => esc_html__('Reload', 'appland-core')),
                array('ti-plus' => esc_html__('Plus', 'appland-core')),
                array('ti-pin' => esc_html__('Pin', 'appland-core')),
                array('ti-pencil' => esc_html__('Pencil', 'appland-core')),
                array('ti-pencil-alt' => esc_html__('Pencil Alt', 'appland-core')),
                array('ti-paint-roller' => esc_html__('Paint Roller', 'appland-core')),
                array('ti-paint-bucket' => esc_html__('Paint Bucket', 'appland-core')),
                array('ti-na' => esc_html__('Na', 'appland-core')),
                array('ti-mobile' => esc_html__('Mobile', 'appland-core')),
                array('ti-minus' => esc_html__('Minus', 'appland-core')),
                array('ti-medall' => esc_html__('Medall', 'appland-core')),
                array('ti-medall-alt' => esc_html__('Medall Alt', 'appland-core')),
                array('ti-marker' => esc_html__('Marker', 'appland-core')),
                array('ti-marker-alt' => esc_html__('Marker Alt', 'appland-core')),
                array('ti-arrow-up' => esc_html__('Arrow Up', 'appland-core')),
                array('ti-arrow-right' => esc_html__('Arrow Right', 'appland-core')),
                array('ti-arrow-left' => esc_html__('Arrow Left', 'appland-core')),
                array('ti-arrow-down' => esc_html__('Arrow Down', 'appland-core')),
                array('ti-lock' => esc_html__('Lock', 'appland-core')),
                array('ti-location-arrow' => esc_html__('Location Arrow', 'appland-core')),
                array('ti-link' => esc_html__('Link', 'appland-core')),
                array('ti-layout' => esc_html__('Layout', 'appland-core')),
                array('ti-layers' => esc_html__('Layers', 'appland-core')),
                array('ti-layers-alt' => esc_html__('Layers Alt', 'appland-core')),
                array('ti-key' => esc_html__('Key', 'appland-core')),
                array('ti-import' => esc_html__('Import', 'appland-core')),
                array('ti-image' => esc_html__('Image', 'appland-core')),
                array('ti-heart' => esc_html__('Heart', 'appland-core')),
                array('ti-heart-broken' => esc_html__('Heart Broken', 'appland-core')),
                array('ti-hand-stop' => esc_html__('Hand Stop', 'appland-core')),
                array('ti-hand-open' => esc_html__('Hand Open', 'appland-core')),
                array('ti-hand-drag' => esc_html__('Hand Drag', 'appland-core')),
                array('ti-folder' => esc_html__('Folder', 'appland-core')),
                array('ti-flag' => esc_html__('Flag', 'appland-core')),
                array('ti-flag-alt' => esc_html__('Flag Alt', 'appland-core')),
                array('ti-flag-alt-2' => esc_html__('Flag Alt 2', 'appland-core')),
                array('ti-eye' => esc_html__('Eye', 'appland-core')),
                array('ti-export' => esc_html__('Export', 'appland-core')),
                array('ti-exchange-vertical' => esc_html__('Exchange Vertical', 'appland-core')),
                array('ti-desktop' => esc_html__('Desktop', 'appland-core')),
                array('ti-cup' => esc_html__('Cup', 'appland-core')),
                array('ti-crown' => esc_html__('Crown', 'appland-core')),
                array('ti-comments' => esc_html__('Comments', 'appland-core')),
                array('ti-comment' => esc_html__('Comment', 'appland-core')),
                array('ti-comment-alt' => esc_html__('Comment Alt', 'appland-core')),
                array('ti-close' => esc_html__('Close', 'appland-core')),
                array('ti-clip' => esc_html__('Clip', 'appland-core')),
                array('ti-angle-up' => esc_html__('Angle Up', 'appland-core')),
                array('ti-angle-right' => esc_html__('Angle Right', 'appland-core')),
                array('ti-angle-left' => esc_html__('Angle Left', 'appland-core')),
                array('ti-angle-down' => esc_html__('Angle Down', 'appland-core')),
                array('ti-check' => esc_html__('Check', 'appland-core')),
                array('ti-check-box' => esc_html__('Check Box', 'appland-core')),
                array('ti-camera' => esc_html__('Camera', 'appland-core')),
                array('ti-announcement' => esc_html__('Announcement', 'appland-core')),
                array('ti-brush' => esc_html__('Brush', 'appland-core')),
                array('ti-briefcase' => esc_html__('Briefcase', 'appland-core')),
                array('ti-bolt' => esc_html__('Bolt', 'appland-core')),
                array('ti-bolt-alt' => esc_html__('Bolt Alt', 'appland-core')),
                array('ti-blackboard' => esc_html__('Blackboard', 'appland-core')),
                array('ti-bag' => esc_html__('Bag', 'appland-core')),
                array('ti-move' => esc_html__('Move', 'appland-core')),
                array('ti-arrows-vertical' => esc_html__('Arrows Vertical', 'appland-core')),
                array('ti-arrows-horizontal' => esc_html__('Arrows Horizontal', 'appland-core')),
                array('ti-fullscreen' => esc_html__('Fullscreen', 'appland-core')),
                array('ti-arrow-top-right' => esc_html__('Arrow Top Right', 'appland-core')),
                array('ti-arrow-top-left' => esc_html__('Arrow Top Left', 'appland-core')),
                array('ti-arrow-circle-up' => esc_html__('Arrow Circle Up', 'appland-core')),
                array('ti-arrow-circle-right' => esc_html__('Arrow Circle Right', 'appland-core')),
                array('ti-arrow-circle-left' => esc_html__('Arrow Circle Left', 'appland-core')),
                array('ti-arrow-circle-down' => esc_html__('Arrow Circle Down', 'appland-core')),
                array('ti-angle-double-up' => esc_html__('Angle Double Up', 'appland-core')),
                array('ti-angle-double-right' => esc_html__('Angle Double Right', 'appland-core')),
                array('ti-angle-double-left' => esc_html__('Angle Double Left', 'appland-core')),
                array('ti-angle-double-down' => esc_html__('Angle Double Down', 'appland-core')),
                array('ti-zip' => esc_html__('Zip', 'appland-core')),
                array('ti-world' => esc_html__('World', 'appland-core')),
                array('ti-wheelchair' => esc_html__('Wheelchair', 'appland-core')),
                array('ti-view-list' => esc_html__('View List', 'appland-core')),
                array('ti-view-list-alt' => esc_html__('View List Alt', 'appland-core')),
                array('ti-view-grid' => esc_html__('View Grid', 'appland-core')),
                array('ti-uppercase' => esc_html__('Uppercase', 'appland-core')),
                array('ti-upload' => esc_html__('Upload', 'appland-core')),
                array('ti-underline' => esc_html__('Underline', 'appland-core')),
                array('ti-truck' => esc_html__('Truck', 'appland-core')),
                array('ti-timer' => esc_html__('Timer', 'appland-core')),
                array('ti-ticket' => esc_html__('Ticket', 'appland-core')),
                array('ti-thumb-up' => esc_html__('Thumb Up', 'appland-core')),
                array('ti-thumb-down' => esc_html__('Thumb Down', 'appland-core')),
                array('ti-text' => esc_html__('Text', 'appland-core')),
                array('ti-stats-up' => esc_html__('Stats Up', 'appland-core')),
                array('ti-stats-down' => esc_html__('Stats Down', 'appland-core')),
                array('ti-split-v' => esc_html__('Split V', 'appland-core')),
                array('ti-split-h' => esc_html__('Split-h', 'appland-core')),
                array('ti-smallcap' => esc_html__('Smallcap', 'appland-core')),
                array('ti-shine' => esc_html__('Shine', 'appland-core')),
                array('ti-shift-right' => esc_html__('Shift Right', 'appland-core')),
                array('ti-shift-left' => esc_html__('Shift Left', 'appland-core')),
                array('ti-shield' => esc_html__('Shield', 'appland-core')),
                array('ti-notepad' => esc_html__('Notepad', 'appland-core')),
                array('ti-server' => esc_html__('Server', 'appland-core')),
                array('ti-quote-right' => esc_html__('Quote Right', 'appland-core')),
                array('ti-quote-left' => esc_html__('Quote Left', 'appland-core')),
                array('ti-pulse' => esc_html__('Pulse', 'appland-core')),
                array('ti-printer' => esc_html__('Printer', 'appland-core')),
                array('ti-power-off' => esc_html__('Power Off', 'appland-core')),
                array('ti-plug' => esc_html__('Plug', 'appland-core')),
                array('ti-pie-chart' => esc_html__('Pie Chart', 'appland-core')),
                array('ti-paragraph' => esc_html__('Paragraph', 'appland-core')),
                array('ti-panel' => esc_html__('Panel', 'appland-core')),
                array('ti-package' => esc_html__('Package', 'appland-core')),
                array('ti-music' => esc_html__('Music', 'appland-core')),
                array('ti-music-alt' => esc_html__('Music Alt', 'appland-core')),
                array('ti-mouse' => esc_html__('Mouse', 'appland-core')),
                array('ti-mouse-alt' => esc_html__('Mouse Alt', 'appland-core')),
                array('ti-money' => esc_html__('Money', 'appland-core')),
                array('ti-microphone' => esc_html__('Microphone', 'appland-core')),
                array('ti-menu' => esc_html__('Menu', 'appland-core')),
                array('ti-menu-alt' => esc_html__('Menu Alt', 'appland-core')),
                array('ti-map' => esc_html__('Map', 'appland-core')),
                array('ti-map-alt' => esc_html__('Map Alt', 'appland-core')),
                array('ti-loop' => esc_html__('Loop', 'appland-core')),
                array('ti-location-pin' => esc_html__('Location Pin', 'appland-core')),
                array('ti-list' => esc_html__('List', 'appland-core')),
                array('ti-light-bulb' => esc_html__('Light Bulb', 'appland-core')),
                array('ti-Italic' => esc_html__('Italic', 'appland-core')),
                array('ti-info' => esc_html__('Info', 'appland-core')),
                array('ti-infinite' => esc_html__('Infinite', 'appland-core')),
                array('ti-id-badge' => esc_html__('Badge', 'appland-core')),
                array('ti-hummer' => esc_html__('Hummer', 'appland-core')),
                array('ti-home' => esc_html__('Home', 'appland-core')),
                array('ti-help' => esc_html__('Help', 'appland-core')),
                array('ti-headphone' => esc_html__('Headphone', 'appland-core')),
                array('ti-harddrives' => esc_html__('Harddrives', 'appland-core')),
                array('ti-harddrive' => esc_html__('Harddrive', 'appland-core')),
                array('ti-gift' => esc_html__('Gift', 'appland-core')),
                array('ti-game' => esc_html__('Game', 'appland-core')),
                array('ti-filter' => esc_html__('Filter', 'appland-core')),
                array('ti-files' => esc_html__('Files', 'appland-core')),
                array('ti-file' => esc_html__('File', 'appland-core')),
                array('ti-eraser' => esc_html__('Eraser', 'appland-core')),
                array('ti-envelope' => esc_html__('Envelope', 'appland-core')),
                array('ti-download' => esc_html__('Download', 'appland-core')),
                array('ti-direction' => esc_html__('Direction', 'appland-core')),
                array('ti-direction-alt' => esc_html__('Direction Alt', 'appland-core')),
                array('ti-dashboard' => esc_html__('Dashboard', 'appland-core')),
                array('ti-control-stop' => esc_html__('Control Stop', 'appland-core')),
                array('ti-control-shuffle' => esc_html__('Control Shuffle', 'appland-core')),
                array('ti-control-play' => esc_html__('Control Play', 'appland-core')),
                array('ti-control-pause' => esc_html__('Control Pause', 'appland-core')),
                array('ti-control-forward' => esc_html__('Control Forward', 'appland-core')),
                array('ti-control-backward' => esc_html__('Control Backward', 'appland-core')),
                array('ti-cloud' => esc_html__('Cloud', 'appland-core')),
                array('ti-cloud-up' => esc_html__('Cloud-up', 'appland-core')),
                array('ti-cloud-down' => esc_html__('Cloud Down', 'appland-core')),
                array('ti-clipboard' => esc_html__('Clipboard', 'appland-core')),
                array('ti-car' => esc_html__('Car', 'appland-core')),
                array('ti-calendar' => esc_html__('Calendar', 'appland-core')),
                array('ti-book' => esc_html__('Book', 'appland-core')),
                array('ti-bell' => esc_html__('Bell', 'appland-core')),
                array('ti-basketball' => esc_html__('Basketball', 'appland-core')),
                array('ti-bar-chart' => esc_html__('Bar Chart', 'appland-core')),
                array('ti-bar-chart-alt' => esc_html__('Bar Chart Alt', 'appland-core')),
                array('ti-back-right' => esc_html__('Back Right', 'appland-core')),
                array('ti-back-left' => esc_html__('Back Left', 'appland-core')),
                array('ti-arrows-corner' => esc_html__('Arrows Corner', 'appland-core')),
                array('ti-archive' => esc_html__('Archive', 'appland-core')),
                array('ti-anchor' => esc_html__('Anchor', 'appland-core')),
                array('ti-align-right' => esc_html__('Align Right', 'appland-core')),
                array('ti-align-left' => esc_html__('Align Left', 'appland-core')),
                array('ti-align-justify' => esc_html__('Align Justify', 'appland-core')),
                array('ti-align-center' => esc_html__('Align Center', 'appland-core')),
                array('ti-alert' => esc_html__('Alert', 'appland-core')),
                array('ti-alarm-clock' => esc_html__('Alarm Clock', 'appland-core')),
                array('ti-agenda' => esc_html__('Agenda', 'appland-core')),
                array('ti-write' => esc_html__('Write', 'appland-core')),
                array('ti-window' => esc_html__('Window', 'appland-core')),
                array('ti-widgetized' => esc_html__('Widgetized', 'appland-core')),
                array('ti-widget' => esc_html__('Widget', 'appland-core')),
                array('ti-widget-alt' => esc_html__('Widget Alt', 'appland-core')),
                array('ti-wallet' => esc_html__('Wallet', 'appland-core')),
                array('ti-video-clapper' => esc_html__('Video Clapper', 'appland-core')),
                array('ti-video-camera' => esc_html__('Video Camera', 'appland-core')),
                array('ti-vector' => esc_html__('Vector', 'appland-core')),
                array('ti-themify-logo' => esc_html__('Themify Logo', 'appland-core')),
                array('ti-themify-favicon' => esc_html__('Themify Favicon', 'appland-core')),
                array('ti-themify-favicon-alt' => esc_html__('Themify Favicon Alt', 'appland-core')),
                array('ti-support' => esc_html__('Support', 'appland-core')),
                array('ti-stamp' => esc_html__('Stamp', 'appland-core')),
                array('ti-split-v-alt' => esc_html__('Split V Alt', 'appland-core')),
                array('ti-slice' => esc_html__('Slice', 'appland-core')),
                array('ti-shortcode' => esc_html__('Shortcode', 'appland-core')),
                array('ti-shift-right-alt' => esc_html__('Shift Right Alt', 'appland-core')),
                array('ti-shift-left-alt' => esc_html__('Shift Left Alt', 'appland-core')),
                array('ti-ruler-alt-2' => esc_html__('Ruler Alt 2', 'appland-core')),
                array('ti-receipt' => esc_html__('Receipt', 'appland-core')),
                array('ti-pin2' => esc_html__('Pin2', 'appland-core')),
                array('ti-pin-alt' => esc_html__('Pin Alt', 'appland-core')),
                array('ti-pencil-alt2' => esc_html__('Pencil Alt2', 'appland-core')),
                array('ti-palette' => esc_html__('Palette', 'appland-core')),
                array('ti-more' => esc_html__('More', 'appland-core')),
                array('ti-more-alt' => esc_html__('More Alt', 'appland-core')),
                array('ti-microphone-alt' => esc_html__('Microphone Alt', 'appland-core')),
                array('ti-magnet' => esc_html__('Magnet', 'appland-core')),
                array('ti-line-double' => esc_html__('Line Double', 'appland-core')),
                array('ti-line-dotted' => esc_html__('Line Dotted', 'appland-core')),
                array('ti-line-dashed' => esc_html__('Line Dashed', 'appland-core')),
                array('ti-layout-width-full' => esc_html__('Layout Width Full', 'appland-core')),
                array('ti-layout-width-default' => esc_html__('Layout Width Default', 'appland-core')),
                array('ti-layout-width-default-alt' => esc_html__('Layout Width Default Alt', 'appland-core')),
                array('ti-layout-tab' => esc_html__('Layout Tab', 'appland-core')),
                array('ti-layout-tab-window' => esc_html__('Layout Tab Window', 'appland-core')),
                array('ti-layout-tab-v' => esc_html__('Layout Tab V', 'appland-core')),
                array('ti-layout-tab-min' => esc_html__('Layout Tab Min', 'appland-core')),
                array('ti-layout-slider' => esc_html__('Layout Slider', 'appland-core')),
                array('ti-layout-slider-alt' => esc_html__('Layout Slider Alt', 'appland-core')),
                array('ti-layout-sidebar-right' => esc_html__('Layout Sidebar Right', 'appland-core')),
                array('ti-layout-sidebar-none' => esc_html__('Layout Sidebar None', 'appland-core')),
                array('ti-layout-sidebar-left' => esc_html__('Layout Sidebar Left', 'appland-core')),
                array('ti-layout-placeholder' => esc_html__('Layout Placeholder', 'appland-core')),
                array('ti-layout-menu' => esc_html__('Layout Menu', 'appland-core')),
                array('ti-layout-menu-v' => esc_html__('layout Menu V', 'appland-core')),
                array('ti-layout-menu-separated' => esc_html__('Layout Menu Separated', 'appland-core')),
                array('ti-layout-menu-full' => esc_html__('Layout Menu Full', 'appland-core')),
                array('ti-layout-media-right-alt' => esc_html__('Layout Media Right Alt', 'appland-core')),
                array('ti-layout-media-right' => esc_html__('Layout Media Right', 'appland-core')),
                array('ti-layout-media-overlay' => esc_html__('Layout Media Overlay', 'appland-core')),
                array('ti-layout-media-overlay-alt' => esc_html__('Layout Media Overlay Alt', 'appland-core')),
                array('ti-layout-media-overlay-alt-2' => esc_html__('Layout Media Overlay Alt 2', 'appland-core')),
                array('ti-layout-media-left-alt' => esc_html__('Layout Media Left Alt', 'appland-core')),
                array('ti-layout-media-left' => esc_html__('Layout Media Left', 'appland-core')),
                array('ti-layout-media-center-alt' => esc_html__('Layout Media Center Alt', 'appland-core')),
                array('ti-layout-media-center' => esc_html__('Layout Media Center', 'appland-core')),
                array('ti-layout-list-thumb' => esc_html__('Layout List Thumb', 'appland-core')),
                array('ti-layout-list-thumb-alt' => esc_html__('Layout List Thumb Alt', 'appland-core')),
                array('ti-layout-list-post' => esc_html__('Layout List Post', 'appland-core')),
                array('ti-layout-list-large-image' => esc_html__('Layout List Large Image', 'appland-core')),
                array('ti-layout-line-solid' => esc_html__('Layout Line Solid', 'appland-core')),
                array('ti-layout-grid4' => esc_html__('Layout Grid4', 'appland-core')),
                array('ti-layout-grid3' => esc_html__('Layout Grid3', 'appland-core')),
                array('ti-layout-grid2' => esc_html__('Layout Grid2', 'appland-core')),
                array('ti-layout-grid2-thumb' => esc_html__('Layout Grid2 Thumb', 'appland-core')),
                array('ti-layout-cta-right' => esc_html__('Layout Cta Right', 'appland-core')),
                array('ti-layout-cta-left' => esc_html__('Layout Cta Left', 'appland-core')),
                array('ti-layout-cta-center' => esc_html__('Layout Cta Center', 'appland-core')),
                array('ti-layout-cta-btn-right' => esc_html__('Layout Cta Btn Right', 'appland-core')),
                array('ti-layout-cta-btn-left' => esc_html__('Layout Cta Btn Left', 'appland-core')),
                array('ti-layout-column4' => esc_html__('Layout Column4', 'appland-core')),
                array('ti-layout-column3' => esc_html__('Layout Column3', 'appland-core')),
                array('ti-layout-column2' => esc_html__('Layout Column2', 'appland-core')),
                array('ti-layout-accordion-separated' => esc_html__('Layout Accordion Separated', 'appland-core')),
                array('ti-layout-accordion-merged' => esc_html__('Layout Accordion Merged', 'appland-core')),
                array('ti-layout-accordion-list' => esc_html__('Layout Accordion List', 'appland-core')),
                array('ti-ink-pen' => esc_html__('Ink Pen', 'appland-core')),
                array('ti-info-alt' => esc_html__('Info Alt', 'appland-core')),
                array('ti-help-alt' => esc_html__('Help Alt', 'appland-core')),
                array('ti-headphone-alt' => esc_html__('Headphone Alt', 'appland-core')),
                array('ti-hand-point-up' => esc_html__('Hand Point Up', 'appland-core')),
                array('ti-hand-point-right' => esc_html__('Hand Point Right', 'appland-core')),
                array('ti-hand-point-left' => esc_html__('Hand Point Left', 'appland-core')),
                array('ti-hand-point-down' => esc_html__('Hand Point Down', 'appland-core')),
                array('ti-gallery' => esc_html__('Gallery', 'appland-core')),
                array('ti-face-smile' => esc_html__('Face Smile', 'appland-core')),
                array('ti-face-sad' => esc_html__('Face Sad', 'appland-core')),
                array('ti-credit-card' => esc_html__('Credit Card', 'appland-core')),
                array('ti-control-skip-forward' => esc_html__('Control Skip Forward', 'appland-core')),
                array('ti-control-skip-forward' => esc_html__('Control Skip Forward', 'appland-core')),
                array('ti-control-skip-forward' => esc_html__('Control Skip Forward', 'appland-core')),
                array('ti-control-record' => esc_html__('Control Record', 'appland-core')),
                array('Control-eject' => esc_html__('Control Eject', 'appland-core')),
                array('ti-comments-smiley' => esc_html__('Comments Smiley', 'appland-core')),
                array('ti-brush-alt' => esc_html__('Brush Alt', 'appland-core')),
                array('ti-youtube' => esc_html__('Youtube', 'appland-core')),
                array('ti-vimeo' => esc_html__('Vimeo', 'appland-core')),
                array('ti-twitter' => esc_html__('Twitter', 'appland-core')),
                array('ti-time' => esc_html__('Time', 'appland-core')),
                array('ti-tumblr' => esc_html__('Tumblr', 'appland-core')),
                array('ti-skype' => esc_html__('Skype', 'appland-core')),
                array('ti-share' => esc_html__('Share', 'appland-core')),
                array('ti-share-alt' => esc_html__('Share Alt', 'appland-core')),
                array('ti-rocket' => esc_html__('Rocket', 'appland-core')),
                array('ti-pinterest' => esc_html__('Pinterest', 'appland-core')),
                array('ti-new-window' => esc_html__('New Window', 'appland-core')),
                array('ti-microsoft' => esc_html__('Microsoft', 'appland-core')),
                array('ti-list-ol' => esc_html__('List Ol', 'appland-core')),
                array('ti-linkedin' => esc_html__('Linkedin', 'appland-core')),
                array('ti-layout-sidebar-2' => esc_html__('Layout Sidebar-2', 'appland-core')),
                array('ti-layout-grid4-alt' => esc_html__('Layout Grid4 Alt', 'appland-core')),
                array('ti-layout-grid3-alt' => esc_html__('Layout Grid3 Alt', 'appland-core')),
                array('ti-layout-grid2-alt' => esc_html__('Layout Grid2 Alt', 'appland-core')),
                array('ti-layout-column4-alt' => esc_html__('Layout Column4 Alt', 'appland-core')),
                array('ti-layout-column3-alt' => esc_html__('Layout Column3 Alt', 'appland-core')),
                array('ti-layout-column2-alt' => esc_html__('Layout Column2 Alt', 'appland-core')),
                array('ti-instagram' => esc_html__('Instagram', 'appland-core')),
                array('ti-google' => esc_html__('Google', 'appland-core')),
                array('ti-github' => esc_html__('Github', 'appland-core')),
                array('ti-flickr' => esc_html__('Flickr', 'appland-core')),
                array('ti-facebook' => esc_html__('Facebook', 'appland-core')),
                array('ti-dropbox' => esc_html__('Dropbox', 'appland-core')),
                array('ti-dribbble' => esc_html__('Dribbble', 'appland-core')),
                array('ti-apple' => esc_html__('Apple', 'appland-core')),
                array('ti-android' => esc_html__('Android', 'appland-core')),
                array('ti-save' => esc_html__('Save', 'appland-core')),
                array('ti-save-alt' => esc_html__('Save Alt', 'appland-core')),
                array('ti-yahoo' => esc_html__('Yahoo', 'appland-core')),
                array('ti-wordpress' => esc_html__('Wordpress', 'appland-core')),
                array('ti-vimeo-alt' => esc_html__('Vimeo Alt', 'appland-core')),
                array('ti-twitter-alt' => esc_html__('Twitter Alt', 'appland-core')),
                array('ti-tumblr-alt' => esc_html__('Tumblr Alt', 'appland-core')),
                array('ti-trello' => esc_html__('Trello', 'appland-core')),
                array('ti-stack-overflow' => esc_html__('Stack Overflow', 'appland-core')),
                array('ti-soundcloud' => esc_html__('Soundcloud', 'appland-core')),
                array('ti-sharethis' => esc_html__('Sharethis', 'appland-core')),
                array('ti-sharethis-alt' => esc_html__('Sharethis Alt', 'appland-core')),
                array('ti-reddit' => esc_html__('Reddit', 'appland-core')),
                array('ti-pinterest-alt' => esc_html__('Pinterest Alt', 'appland-core')),
                array('ti-microsoft-alt' => esc_html__('Microsoft Alt', 'appland-core')),
                array('ti-linux' => esc_html__('Linux', 'appland-core')),
                array('ti-jsfiddle' => esc_html__('Jsfiddle', 'appland-core')),
                array('ti-joomla' => esc_html__('Joomla', 'appland-core')),
                array('ti-html5' => esc_html__('Html5', 'appland-core')),
                array('ti-flickr-alt' => esc_html__('Flickr Alt', 'appland-core')),
                array('ti-email' => esc_html__('Email', 'appland-core')),
                array('ti-drupal' => esc_html__('Drupal', 'appland-core')),
                array('ti-dropbox-alt' => esc_html__('Dropbox Alt', 'appland-core')),
                array('ti-css3' => esc_html__('Css3', 'appland-core')),
                array('ti-rss' => esc_html__('Rss', 'appland-core')),
                array('ti-rss-alt' => esc_html__('Rss-alt', 'appland-core'))
            );
        });

        /**
         * Enqueue Backend and Frontend CSS Styles
         */
        add_action('vc_backend_editor_enqueue_js_css', function () {
            wp_enqueue_style('themify-icon', plugins_url('appland-core/assets/themify-icon/themify-icons.css'));
        });
        add_action('vc_frontend_editor_enqueue_js_css', function () {
            wp_enqueue_style('themify-icon', plugins_url('appland-core/assets/themify-icon/themify-icons.css'));
        });

        /**
         * Enqueue CSS in Frontend when it's used
         */
        add_action('vc_enqueue_font_icon_element', function ($font) {
            switch ($font) {
                case 'themify-icon':
                    wp_enqueue_style('themify-icon');
            }
        });


        /**
         * Adding Linericons to Visual composer icon-picker
         * *************************************************
         */

// Add new custom font to Font Family selection in icon box module
        add_filter('init', function () {
            $param = WPBMap::getParam('vc_icon', 'type');
            $param['value'][__('Linear Icons', 'appland-core')] = 'linearicons';
            vc_update_shortcode_param('vc_icon', $param);
        }, 40);

// Add array of your fonts so they can be displayed in the font selector
        add_filter('vc_iconpicker-type-linearicons', function () {
            return array(
                array('lnr lnr-home' => esc_html__('Home', 'appland-core')),
                array('lnr lnr-smartphone' => esc_html__('Smart Phone', 'appland-core')),
                array('lnr lnr-apartment' => esc_html__('Apartment', 'appland-core')),
                array('lnr lnr-pencil' => esc_html__('Pencil', 'appland-core')),
                array('lnr lnr-magic-wand' => esc_html__('Magic Wand', 'appland-core')),
                array('lnr lnr-drop' => esc_html__('Drop', 'appland-core')),
                array('lnr lnr-lighter' => esc_html__('Lighter', 'appland-core')),
                array('lnr lnr-poop' => esc_html__('Poop', 'appland-core')),
                array('lnr lnr-sun' => esc_html__('Sun', 'appland-core')),
                array('lnr lnr-moon' => esc_html__('Moon', 'appland-core')),
                array('lnr lnr-cloud' => esc_html__('Cloud', 'appland-core')),
                array('lnr lnr-cloud-upload' => esc_html__('Cloud Upload', 'appland-core')),
                array('lnr lnr-cloud-download' => esc_html__('Cloud Download', 'appland-core')),
                array('lnr lnr-cloud-sync' => esc_html__('Cloud Sync', 'appland-core')),
                array('lnr lnr-cloud-check' => esc_html__('Cloud Check', 'appland-core')),
                array('lnr lnr-database' => esc_html__('Database', 'appland-core')),
                array('lnr lnr-lock' => esc_html__('Lock', 'appland-core')),
                array('lnr lnr-cog' => esc_html__('Cog', 'appland-core')),
                array('lnr lnr-trash' => esc_html__('Trash', 'appland-core')),
                array('lnr lnr-dice' => esc_html__('Dice', 'appland-core')),
                array('lnr lnr-heart' => esc_html__('Heart', 'appland-core')),
                array('lnr lnr-star' => esc_html__('Star', 'appland-core')),
                array('lnr lnr-star-half' => esc_html__('Star Half', 'appland-core')),
                array('lnr lnr-star-empty' => esc_html__('Star Empty', 'appland-core')),
                array('lnr lnr-flag' => esc_html__('Flag', 'appland-core')),
                array('lnr lnr-envelope' => esc_html__('Envelope', 'appland-core')),
                array('lnr lnr-paperclip' => esc_html__('Paperclip', 'appland-core')),
                array('lnr lnr-inbox' => esc_html__('Inbox', 'appland-core')),
                array('lnr lnr-eye' => esc_html__('Eye', 'appland-core')),
                array('lnr lnr-printer' => esc_html__('Printer', 'appland-core')),
                array('lnr lnr-file-empty' => esc_html__('File Empty', 'appland-core')),
                array('lnr lnr-file-add' => esc_html__('File Add', 'appland-core')),
                array('lnr lnr-exit' => esc_html__('Exit', 'appland-core')),
                array('lnr lnr-graduation-hat' => esc_html__('Graduation Hat', 'appland-core')),
                array('lnr lnr-license' => esc_html__('Licence', 'appland-core')),
                array('lnr lnr-music-note' => esc_html__('Music Note', 'appland-core')),
                array('lnr lnr-film-play' => esc_html__('Film Play', 'appland-core')),
                array('lnr lnr-camera-video' => esc_html__('Camera Video', 'appland-core')),
                array('lnr lnr-camera' => esc_html__('Camera', 'appland-core')),
                array('lnr lnr-picture' => esc_html__('Picture', 'appland-core')),
                array('lnr lnr-book' => esc_html__('Book', 'appland-core')),
                array('lnr lnr-bookmark' => esc_html__('Bookmark', 'appland-core')),
                array('lnr lnr-user' => esc_html__('User', 'appland-core')),
                array('lnr lnr-users' => esc_html__('Users', 'appland-core')),
                array('lnr lnr-shirt' => esc_html__('Shirt', 'appland-core')),
                array('lnr lnr-store' => esc_html__('Store', 'appland-core')),
                array('lnr lnr-cart' => esc_html__('Cart', 'appland-core')),
                array('lnr lnr-tag' => esc_html__('Tag', 'appland-core')),
                array('lnr lnr-phone-handset' => esc_html__('Phone Handset', 'appland-core')),
                array('lnr lnr-phone' => esc_html__('Phone', 'appland-core')),
                array('lnr lnr-pushpin' => esc_html__('Pushpin', 'appland-core')),
                array('lnr lnr-map-marker' => esc_html__('Map Marker', 'appland-core')),
                array('lnr lnr-map' => esc_html__('Map', 'appland-core')),
                array('lnr lnr-location' => esc_html__('Location', 'appland-core')),
                array('lnr lnr-calendar-full' => esc_html__('Calendar Full', 'appland-core')),
                array('lnr lnr-keyboard' => esc_html__('Keyboard', 'appland-core')),
                array('lnr lnr-spell-chekc' => esc_html__('Spell Check', 'appland-core')),
                array('lnr lnr-screen' => esc_html__('Screen', 'appland-core')),
                array('lnr lnr-smartphone' => esc_html__('Smartphone', 'appland-core')),
                array('lnr lnr-tablet' => esc_html__('Tablet', 'appland-core')),
                array('lnr lnr-laptop' => esc_html__('Laptop', 'appland-core')),
                array('lnr lnr-laptop-phone' => esc_html__('Laptop Phone', 'appland-core')),
                array('lnr lnr-power-switch' => esc_html__('Power Switch', 'appland-core')),
                array('lnr lnr-bubble' => esc_html__('Bubble', 'appland-core')),
                array('lnr lnr-heart-pulse' => esc_html__('Heart Pulse', 'appland-core')),
                array('lnr lnr-construction' => esc_html__('Construction', 'appland-core')),
                array('lnr lnr-pie-chart' => esc_html__('Pie Chart', 'appland-core')),
                array('lnr lnr-chart-bars' => esc_html__('Chart Bars', 'appland-core')),
                array('lnr lnr-gift' => esc_html__('Gift', 'appland-core')),
                array('lnr lnr-diamond' => esc_html__('Diamond', 'appland-core')),
                array('lnr lnr-linearicons' => esc_html__('Linear Icons', 'appland-core')),
                array('lnr lnr-dinner' => esc_html__('Dinner', 'appland-core')),
                array('lnr lnr-coffee-cup' => esc_html__('Coffee Cup', 'appland-core')),
                array('lnr lnr-leaf' => esc_html__('Leaf', 'appland-core')),
                array('lnr lnr-paw' => esc_html__('Paw', 'appland-core')),
                array('lnr lnr-rocket' => esc_html__('Rocket', 'appland-core')),
                array('lnr lnr-briefcase' => esc_html__('Briefcase', 'appland-core')),
                array('lnr lnr-bus' => esc_html__('Bus', 'appland-core')),
                array('lnr lnr-car' => esc_html__('Car', 'appland-core')),
                array('lnr lnr-train' => esc_html__('Train', 'appland-core')),
                array('lnr lnr-bicycle' => esc_html__('Bicycle', 'appland-core')),
                array('lnr lnr-wheelchair' => esc_html__('Wheelchair', 'appland-core')),
                array('lnr lnr-select' => esc_html__('Select', 'appland-core')),
                array('lnr lnr-earth' => esc_html__('Earth', 'appland-core')),
                array('lnr lnr-smile' => esc_html__('Smile', 'appland-core')),
                array('lnr lnr-sad' => esc_html__('Sad', 'appland-core')),
                array('lnr lnr-neutral' => esc_html__('Neutral', 'appland-core')),
                array('lnr lnr-mustache' => esc_html__('Mustache', 'appland-core')),
                array('lnr lnr-alarm' => esc_html__('Alarm', 'appland-core')),
                array('lnr lnr-bullborn' => esc_html__('Bullhorn', 'appland-core')),
                array('lnr lnr-volume-high' => esc_html__('Volume High', 'appland-core')),
                array('lnr lnr-volume-medium' => esc_html__('Volume Medium', 'appland-core')),
                array('lnr lnr-volume-low' => esc_html__('Volume Low', 'appland-core')),
                array('lnr lnr-volume' => esc_html__('Volume', 'appland-core')),
                array('lnr lnr-mic' => esc_html__('Mic', 'appland-core')),
                array('lnr lnr-hourglass' => esc_html__('Hourglass', 'appland-core')),
                array('lnr lnr-undo' => esc_html__('Undo', 'appland-core')),
                array('lnr lnr-redo' => esc_html__('Redo', 'appland-core')),
                array('lnr lnr-sync' => esc_html__('Sync', 'appland-core')),
                array('lnr lnr-history' => esc_html__('History', 'appland-core')),
                array('lnr lnr-clock' => esc_html__('Clock', 'appland-core')),
                array('lnr lnr-download' => esc_html__('Download', 'appland-core')),
                array('lnr lnr-upload' => esc_html__('Upload', 'appland-core')),
                array('lnr lnr-enter-down' => esc_html__('Enter Down', 'appland-core')),
                array('lnr lnr-exit-up' => esc_html__('Exit Up', 'appland-core')),
                array('lnr lnr-bug' => esc_html__('Bug', 'appland-core')),
                array('lnr lnr-code' => esc_html__('Code', 'appland-core')),
                array('lnr lnr-link' => esc_html__('Link', 'appland-core')),
                array('lnr lnr-unlink' => esc_html__('Unlink', 'appland-core')),
                array('lnr lnr-thumbs-up' => esc_html__('Thumbs Up', 'appland-core')),
                array('lnr lnr-thumbs-down' => esc_html__('Thumbs Down', 'appland-core')),
                array('lnr lnr-thumbs-magnifier' => esc_html__('Magnifier', 'appland-core')),
                array('lnr lnr-cross' => esc_html__('Cross', 'appland-core')),
                array('lnr lnr-menu' => esc_html__('Menu', 'appland-core')),
                array('lnr lnr-list' => esc_html__('List', 'appland-core')),
                array('lnr lnr-chevron-up' => esc_html__('Chevron Up', 'appland-core')),
                array('lnr lnr-chevron-down' => esc_html__('Chevron Down', 'appland-core')),
                array('lnr lnr-chevron-left' => esc_html__('Chevron Left', 'appland-core')),
                array('lnr lnr-chevron-right' => esc_html__('Chevron Right', 'appland-core')),
                array('lnr lnr-arrow-up' => esc_html__('Arrow Up', 'appland-core')),
                array('lnr lnr-arrow-down' => esc_html__('Arrow Down', 'appland-core')),
                array('lnr lnr-arrow-left' => esc_html__('Arrow Left', 'appland-core')),
                array('lnr lnr-arrow-right' => esc_html__('Arrow Right', 'appland-core')),
                array('lnr lnr-move' => esc_html__('Move', 'appland-core')),
                array('lnr lnr-warning' => esc_html__('Warning', 'appland-core')),
                array('lnr lnr-question-circle' => esc_html__('Question Circle', 'appland-core')),
                array('lnr lnr-menu-circle' => esc_html__('Menu Circle', 'appland-core')),
                array('lnr lnr-checkmark-circle' => esc_html__('Checkmark Circle', 'appland-core')),
                array('lnr lnr-cross-circle' => esc_html__('Cross Circle', 'appland-core')),
                array('lnr lnr-plus-circle' => esc_html__('Plus Circle', 'appland-core')),
                array('lnr lnr-circle-minus' => esc_html__('Circle Minus', 'appland-core')),
                array('lnr lnr-arrow-up-circle' => esc_html__('Arrow Up Circle', 'appland-core')),
                array('lnr lnr-arrow-down-circle' => esc_html__('Arrow Down Circle', 'appland-core')),
                array('lnr lnr-arrow-left-circle' => esc_html__('Arrow Left Circle', 'appland-core')),
                array('lnr lnr-arrow-right-circle' => esc_html__('Arrow Right Circle', 'appland-core')),
                array('lnr lnr-chevron-up-circle' => esc_html__('Chevron Up Circle', 'appland-core')),
                array('lnr lnr-chevron-down-circle' => esc_html__('Chevron Down Circle', 'appland-core')),
                array('lnr lnr-chevron-left-circle' => esc_html__('Chevron Left Circle', 'appland-core')),
                array('lnr lnr-chevron-right-circle' => esc_html__('Chevron Right Circle', 'appland-core')),
                array('lnr lnr-crop' => esc_html__('Crop', 'appland-core')),
                array('lnr lnr-frame-expand' => esc_html__('Frame Expand', 'appland-core')),
                array('lnr lnr-frame-contract' => esc_html__('Frame Contract', 'appland-core')),
                array('lnr lnr-layers' => esc_html__('Layers', 'appland-core')),
                array('lnr lnr-funnel' => esc_html__('Funnel', 'appland-core')),
                array('lnr lnr-text-format' => esc_html__('Text Format', 'appland-core')),
                array('lnr lnr-text-format-remove' => esc_html__('Text Format Remove', 'appland-core')),
                array('lnr lnr-text-size' => esc_html__('Text Size', 'appland-core')),
                array('lnr lnr-bold' => esc_html__('Bold', 'appland-core')),
                array('lnr lnr-italic' => esc_html__('Italic', 'appland-core')),
                array('lnr lnr-underline' => esc_html__('Underline', 'appland-core')),
                array('lnr lnr-strikethrough' => esc_html__('Strikethrough', 'appland-core')),
                array('lnr lnr-highlight' => esc_html__('Highlight', 'appland-core')),
                array('lnr lnr-text-aligh-left' => esc_html__('Text Aligh left', 'appland-core')),
                array('lnr lnr-text-aligh-center' => esc_html__('Text Aligh Center', 'appland-core')),
                array('lnr lnr-text-aligh-right' => esc_html__('Text Aligh Right', 'appland-core')),
                array('lnr lnr-text-aligh-justify' => esc_html__('Text Aligh Justify', 'appland-core')),
                array('lnr lnr-line-spacing' => esc_html__('Line Spacing', 'appland-core')),
                array('lnr lnr-indent-increase' => esc_html__('Indent Increase', 'appland-core')),
                array('lnr lnr-indent-increase' => esc_html__('Indent Increase', 'appland-core')),
                array('lnr lnr-indent-decrease' => esc_html__('Indent Decrease', 'appland-core')),
                array('lnr lnr-pilcrow' => esc_html__('Pilcrow', 'appland-core')),
                array('lnr lnr-direction-ltr' => esc_html__('Direction LTR', 'appland-core')),
                array('lnr lnr-direction-rtl' => esc_html__('Direction RTL', 'appland-core')),
                array('lnr lnr-page-break' => esc_html__('Page Break', 'appland-core')),
                array('lnr lnr-sort-alpha-asc' => esc_html__('Sort Alpha ASC', 'appland-core')),
                array('lnr lnr-sort-amount-asc' => esc_html__('Sort Amount ASC', 'appland-core')),
                array('lnr lnr-hand' => esc_html__('Hand', 'appland-core')),
                array('lnr lnr-pointer-up' => esc_html__('Pointer Up', 'appland-core')),
                array('lnr lnr-pointer-right' => esc_html__('Pointer Right', 'appland-core')),
                array('lnr lnr-pointer-down' => esc_html__('Pointer Down', 'appland-core')),
                array('lnr lnr-pointer-left' => esc_html__('Pointer Left', 'appland-core')),
            );
        });

        /**
         * Enqueue Backend and Frontend CSS Styles
         */
        add_action('vc_backend_editor_enqueue_js_css', function () {
            wp_enqueue_style('linearicons', plugins_url('appland-core/assets/css/linearicons.css'));
        });
        add_action('vc_frontend_editor_enqueue_js_css', function () {
            wp_enqueue_style('linearicons', plugins_url('appland-core/assets/css/linearicons.css'));
        });

        /**
         * Enqueue CSS in Frontend when it's used
         */
        add_action('vc_enqueue_font_icon_element', function ($font) {
            switch ($font) {
                case 'linearicons':
                    wp_enqueue_style('linearicons');
            }
        });
    }
});